import type { Product } from "@/lib/types";

function product(input: Product): Product {
  return {
    refurbished: false,
    msrp: input.msrp ?? input.price,
    accessoryBurden: input.accessoryBurden ?? 0,
    ...input
  };
}

export const products: Product[] = [
  product({
    id: "iphone-17e",
    name: "iPhone 17e",
    brand: "Apple",
    category: "smartphones",
    tier: "Entry flagship",
    price: 599,
    attributes: { performance: 78, battery: 80, portability: 88, camera: 74, display: 78, gaming: 68, longevity: 92, value: 80, software: 94 },
    ecosystems: ["apple"],
    useCaseTags: ["school", "commute", "travel"],
    strengths: ["Low-friction Apple entry point", "Compact and easy to carry", "Long software confidence"],
    tradeoffs: ["Camera is clearly below Pro-tier phones", "Display story is functional, not exciting"],
    pricingTrapNotes: ["The storage step-up becomes expensive quickly.", "If you want stronger camera output, jumping to the standard iPhone may be cleaner than maxing this one out."],
    marketingPositioning: ["Apple's safe default for price-conscious ecosystem buyers", "Uses Apple's premium umbrella to make the standard model feel like the 'real' iPhone"],
    summary: "A straightforward Apple option for users who want low switching friction without funding the full premium ladder.",
    shortPitch: "Best Apple entry if you value simplicity over camera ambition.",
    priceStory: "Firm list price with trade-in and financing doing most of the affordability work.",
    upsellPressure: 78,
    discountPressure: 32,
    lockInPressure: 95
  }),
  product({
    id: "iphone-17",
    name: "iPhone 17",
    brand: "Apple",
    category: "smartphones",
    tier: "Mainstream flagship",
    price: 829,
    attributes: { performance: 86, battery: 84, portability: 86, camera: 87, display: 89, gaming: 78, longevity: 93, value: 76, software: 95 },
    ecosystems: ["apple"],
    useCaseTags: ["commute", "travel", "school", "content-creation"],
    strengths: ["Strong all-around Apple phone", "Balanced battery and camera story", "Easiest long-term Apple recommendation"],
    tradeoffs: ["Does not separate dramatically from the 17e for lighter users", "Premium feel still climbs quickly with storage upgrades"],
    pricingTrapNotes: ["The standard model can look safer mainly because the Pro is anchored much higher.", "Carrier credits can disguise how firm the headline pricing still is."],
    marketingPositioning: ["Apple's default flagship center of gravity", "The model most people are meant to rationalize as sensible"],
    summary: "The safest iPhone choice for buyers who want the Apple ecosystem without paying for every Pro signal.",
    shortPitch: "Balanced Apple flagship with the fewest obvious compromises.",
    priceStory: "List price stays clean while trade-ins and financing lower the monthly sting.",
    upsellPressure: 82,
    discountPressure: 36,
    lockInPressure: 95
  }),
  product({
    id: "iphone-17-pro",
    name: "iPhone 17 Pro",
    brand: "Apple",
    category: "smartphones",
    tier: "Pro flagship",
    price: 1099,
    attributes: { performance: 95, battery: 90, portability: 79, camera: 97, display: 95, gaming: 84, longevity: 93, value: 66, software: 96 },
    ecosystems: ["apple"],
    useCaseTags: ["content-creation", "commute", "travel"],
    strengths: ["Top-tier camera package", "Excellent display and processing headroom", "High-end Apple ecosystem fit"],
    tradeoffs: ["Significant jump over the standard iPhone", "The daily-life gain is smaller than the price gain for many people"],
    pricingTrapNotes: ["This is where Apple's premium anchoring becomes most visible.", "If you do not use the camera and display upgrades, the extra spend is hard to justify."],
    marketingPositioning: ["Apple's status and capability flagship short of the very largest model", "Built to make the standard iPhone feel reasonable and the biggest Pro feel aspirational"],
    summary: "The right iPhone when you genuinely need top-tier camera and premium display quality instead of just wanting the badge.",
    shortPitch: "Best iPhone for creators who will actually use the extra hardware.",
    priceStory: "A premium ladder step that relies heavily on perceived pro identity.",
    upsellPressure: 90,
    discountPressure: 28,
    lockInPressure: 96
  }),
  product({
    id: "galaxy-s25-fe",
    name: "Galaxy S25 FE",
    brand: "Samsung",
    category: "smartphones",
    tier: "Value flagship",
    price: 649,
    msrp: 699,
    attributes: { performance: 82, battery: 86, portability: 84, camera: 79, display: 85, gaming: 83, longevity: 79, value: 89, software: 84 },
    ecosystems: ["android", "samsung"],
    useCaseTags: ["school", "gaming", "travel", "commute"],
    strengths: ["Strong value floor", "Battery is safer than most mid-premium phones", "Samsung promo windows often improve the deal further"],
    tradeoffs: ["Camera sits below the core S25 and Ultra", "Build and prestige are clearly the compromise"],
    pricingTrapNotes: ["The FE only works as great value if the spec gap to the standard S25 stays acceptable for your use case.", "Launch promos can make the base S25 much closer in price than expected."],
    marketingPositioning: ["Samsung's answer when shoppers want flagship credibility without flagship price", "Designed to hold value buyers inside the Galaxy funnel"],
    summary: "A practical Galaxy pick when battery and value matter more than flexing the premium tier.",
    shortPitch: "Best Samsung value play for most budget-aware buyers.",
    priceStory: "Samsung typically reinforces this tier with visible direct-store promos.",
    upsellPressure: 58,
    discountPressure: 74,
    lockInPressure: 70
  }),
  product({
    id: "galaxy-s25",
    name: "Galaxy S25",
    brand: "Samsung",
    category: "smartphones",
    tier: "Mainstream flagship",
    price: 799,
    msrp: 849,
    attributes: { performance: 90, battery: 87, portability: 88, camera: 86, display: 92, gaming: 90, longevity: 81, value: 82, software: 86 },
    ecosystems: ["android", "samsung"],
    useCaseTags: ["commute", "travel", "gaming", "content-creation"],
    strengths: ["Balanced flagship hardware", "Display and gaming comfort are strong", "Promotions often make it more attractive than the list price suggests"],
    tradeoffs: ["Still easy to drift upward to the Ultra", "Longevity confidence is good, but the resale story is softer than Apple"],
    pricingTrapNotes: ["Samsung's promo cadence can make paying full price feel unnecessary.", "The jump to the Ultra looks tempting because Samsung makes the premium features very visible."],
    marketingPositioning: ["Samsung's core mainstream flagship", "The model meant to feel rational after seeing the Ultra first"],
    summary: "A balanced Samsung flagship that becomes especially compelling when direct-store promotions are active.",
    shortPitch: "Safest Galaxy pick if you want flagship feel without Ultra size.",
    priceStory: "Samsung often narrows the gap between MSRP and effective price through promos and trade-ins.",
    upsellPressure: 72,
    discountPressure: 80,
    lockInPressure: 72
  }),
  product({
    id: "galaxy-s25-ultra",
    name: "Galaxy S25 Ultra",
    brand: "Samsung",
    category: "smartphones",
    tier: "Ultra flagship",
    price: 1199,
    msrp: 1299,
    attributes: { performance: 99, battery: 96, portability: 66, camera: 99, display: 97, gaming: 95, longevity: 84, value: 71, software: 88 },
    ecosystems: ["android", "samsung"],
    useCaseTags: ["content-creation", "gaming", "travel"],
    strengths: ["Camera reach is elite", "Battery and performance headroom are both top-tier", "S Pen and large-screen multitasking help heavy users"],
    tradeoffs: ["Big and less comfortable than mainstream phones", "Very easy to overbuy if your daily tasks are ordinary"],
    pricingTrapNotes: ["A large part of the premium is for capability ceiling, not average-day usefulness.", "Samsung's launch bundles can make this look more rational than it remains after the promo window."],
    marketingPositioning: ["The halo device that makes every lower Galaxy feel reasonable", "A feature-maxing statement product"],
    summary: "An excellent phone for people who will really exploit the camera, display, and battery ceiling.",
    shortPitch: "Best Galaxy when the size and price both make sense for your workload.",
    priceStory: "Promos can soften the price, but it remains a deliberate premium purchase.",
    upsellPressure: 88,
    discountPressure: 69,
    lockInPressure: 74
  }),
  product({
    id: "pixel-10",
    name: "Pixel 10",
    brand: "Google",
    category: "smartphones",
    tier: "Mainstream flagship",
    price: 799,
    attributes: { performance: 86, battery: 88, portability: 86, camera: 91, display: 89, gaming: 75, longevity: 91, value: 84, software: 96 },
    ecosystems: ["android", "google"],
    useCaseTags: ["content-creation", "travel", "commute", "school"],
    strengths: ["Camera and software feel smarter than the spec sheet alone suggests", "Good battery and update runway", "Strong default Android value"],
    tradeoffs: ["Not the strongest gaming phone", "Google saves its flashiest hardware for the Pro tier"],
    pricingTrapNotes: ["The Pro can become tempting mainly because Google frames AI and camera upgrades as identity products.", "At full price this is good value, but promo windows can make the Pro more tempting than usual."],
    marketingPositioning: ["Google's clean everyday flagship", "AI-first pitch without fully premium pricing"],
    summary: "A balanced Pixel for buyers who care about camera quality, AI features, and long update support.",
    shortPitch: "Strongest Google all-rounder for most buyers.",
    priceStory: "Usually priced fairly, then improved by Google Store promos.",
    upsellPressure: 62,
    discountPressure: 66,
    lockInPressure: 68
  }),
  product({
    id: "pixel-10-pro",
    name: "Pixel 10 Pro",
    brand: "Google",
    category: "smartphones",
    tier: "Pro flagship",
    price: 949,
    msrp: 999,
    attributes: { performance: 93, battery: 91, portability: 82, camera: 97, display: 94, gaming: 80, longevity: 92, value: 80, software: 98 },
    ecosystems: ["android", "google"],
    useCaseTags: ["content-creation", "travel", "commute"],
    strengths: ["Excellent camera and software mix", "Strong AI workflow story", "Promo-adjusted value is better than the list suggests"],
    tradeoffs: ["Still a meaningful step above the base Pixel", "If you do not use the camera or AI extras, it can be overkill"],
    pricingTrapNotes: ["The Pro is often helped by visible store promos that improve the story materially.", "Without the promo, the standard Pixel is the calmer value choice."],
    marketingPositioning: ["Google's premium camera and AI phone", "A cleaner upsell than many rivals because the software benefits feel tangible"],
    summary: "The right Pixel when you want Google's best camera and AI features without jumping to a foldable.",
    shortPitch: "Best Pixel for creators and heavy Google-services users.",
    priceStory: "Direct-store promos matter a lot to how rational this feels.",
    upsellPressure: 70,
    discountPressure: 72,
    lockInPressure: 70
  }),
  product({
    id: "macbook-air-13",
    name: "MacBook Air 13",
    brand: "Apple",
    category: "laptops",
    tier: "Portable mainstream",
    price: 1199,
    attributes: { performance: 88, battery: 95, portability: 94, display: 86, gaming: 50, longevity: 93, software: 96, value: 82 },
    ecosystems: ["apple"],
    useCaseTags: ["school", "coding", "travel", "hybrid-work"],
    strengths: ["Excellent battery and portability", "High-confidence everyday performance", "Strong Apple workflow fit"],
    tradeoffs: ["Gaming is not the point", "Thermal ceiling is still below heavier pro machines"],
    pricingTrapNotes: ["Memory and storage upgrades are where the price climbs fastest.", "If your work is light, the premium over good Windows ultrabooks may be mostly about ecosystem comfort."],
    marketingPositioning: ["Apple's default premium ultraportable", "The model most buyers are intended to feel comfortable with"],
    summary: "A low-drama laptop recommendation when battery, portability, and OS polish matter more than raw graphics.",
    shortPitch: "Best Apple laptop for most buyers who move a lot.",
    priceStory: "Apple keeps the main price firm and leans on the product's reputation.",
    upsellPressure: 84,
    discountPressure: 26,
    lockInPressure: 95
  }),
  product({
    id: "macbook-pro-14",
    name: "MacBook Pro 14",
    brand: "Apple",
    category: "laptops",
    tier: "Creator pro",
    price: 1799,
    attributes: { performance: 98, battery: 91, portability: 76, display: 97, gaming: 66, longevity: 94, software: 96, value: 70 },
    ecosystems: ["apple"],
    useCaseTags: ["coding", "content-creation", "hybrid-work"],
    strengths: ["Excellent performance headroom", "Display quality is elite", "Build and longevity confidence are high"],
    tradeoffs: ["Heavy compared with thinner options", "Easy to overspend for general office work"],
    pricingTrapNotes: ["This is where Apple's premium anchor becomes most visible in laptops.", "If your main work is browser, docs, and light dev, the Air is usually the better spend."],
    marketingPositioning: ["Apple's serious work machine", "A capability signal as much as a practical tool"],
    summary: "A great fit for heavier creative and engineering workloads, but not the default rational laptop for everyone.",
    shortPitch: "Best Mac if you will actually use the headroom.",
    priceStory: "A high list price justified through workflow confidence and display quality, not discounting.",
    upsellPressure: 92,
    discountPressure: 20,
    lockInPressure: 95
  }),
  product({
    id: "surface-laptop-13",
    name: "Surface Laptop 13",
    brand: "Microsoft",
    category: "laptops",
    tier: "Portable productivity",
    price: 999,
    attributes: { performance: 80, battery: 88, portability: 92, display: 82, gaming: 42, longevity: 81, software: 88, value: 84 },
    ecosystems: ["windows", "microsoft"],
    useCaseTags: ["school", "travel", "hybrid-work"],
    strengths: ["Portable and efficient", "Windows plus Copilot+ story is coherent", "Good value for a polished Windows ultraportable"],
    tradeoffs: ["Not meant for serious gaming", "Creator workloads will hit the ceiling faster than larger laptops"],
    pricingTrapNotes: ["Accessory and larger-screen upsells can move you out of the best-value zone quickly.", "Surface pricing looks better when promotions are active."],
    marketingPositioning: ["Microsoft's clean everyday AI PC", "A lifestyle Windows laptop rather than a value brute-force option"],
    summary: "A polished Windows ultraportable if you want simplicity, battery, and less chassis bulk.",
    shortPitch: "Best Surface for practical portability.",
    priceStory: "Often supported by modest promos and price-protection messaging.",
    upsellPressure: 56,
    discountPressure: 62,
    lockInPressure: 60
  }),
  product({
    id: "surface-laptop-15",
    name: "Surface Laptop 15",
    brand: "Microsoft",
    category: "laptops",
    tier: "Large-screen productivity",
    price: 1299,
    msrp: 1399,
    attributes: { performance: 89, battery: 92, portability: 72, display: 88, gaming: 48, longevity: 82, software: 89, value: 78 },
    ecosystems: ["windows", "microsoft"],
    useCaseTags: ["coding", "hybrid-work", "travel"],
    strengths: ["Great battery and screen comfort", "More breathing room than the 13-inch model", "Strong daily-use Windows machine"],
    tradeoffs: ["Less travel-friendly", "Still not a real gaming or creator workstation"],
    pricingTrapNotes: ["If you are stretching just for more screen, the extra cost can be difficult to justify.", "This model works best when promo pricing narrows the gap."],
    marketingPositioning: ["The grown-up productivity Surface", "Sold on comfort, not aggression"],
    summary: "A larger, calmer Surface for buyers who want a better work canvas without entering workstation territory.",
    shortPitch: "Best Surface if screen comfort matters more than absolute portability.",
    priceStory: "The effective price often matters more than the MSRP here.",
    upsellPressure: 60,
    discountPressure: 70,
    lockInPressure: 60
  }),
  product({
    id: "xps-13",
    name: "Dell XPS 13",
    brand: "Dell",
    category: "laptops",
    tier: "Premium compact",
    price: 1099,
    msrp: 1249,
    attributes: { performance: 84, battery: 84, portability: 90, display: 90, gaming: 45, longevity: 79, software: 78, value: 80 },
    ecosystems: ["windows"],
    useCaseTags: ["travel", "school", "coding", "hybrid-work"],
    strengths: ["Compact premium design", "Display quality is a highlight", "Often discounted meaningfully from list"],
    tradeoffs: ["The premium configuration ladder climbs fast", "Thermal comfort is not class-leading"],
    pricingTrapNotes: ["Dell's OLED and memory upgrades can quickly rewrite the value story.", "The base discounted config can be far more rational than the glossy top-end one."],
    marketingPositioning: ["Dell's design-first ultraportable", "Premium feel used to justify aggressive config upsells"],
    summary: "A stylish Windows ultraportable that makes the most sense when the discounted base or mid config is enough.",
    shortPitch: "Strong Dell pick if you want premium Windows design without drifting into creator pricing.",
    priceStory: "Dell's discounting means the real value depends on configuration discipline.",
    upsellPressure: 82,
    discountPressure: 84,
    lockInPressure: 28
  }),
  product({
    id: "xps-14",
    name: "Dell XPS 14",
    brand: "Dell",
    category: "laptops",
    tier: "Creator premium",
    price: 1599,
    msrp: 1799,
    attributes: { performance: 92, battery: 80, portability: 74, display: 94, gaming: 78, longevity: 80, software: 80, value: 74 },
    ecosystems: ["windows"],
    useCaseTags: ["content-creation", "coding", "gaming", "hybrid-work"],
    strengths: ["Strong creator-friendly display", "Better GPU ceiling than ultralights", "Discounted pricing can rescue the value case"],
    tradeoffs: ["Can become expensive quickly", "Battery is only moderate for the class"],
    pricingTrapNotes: ["This is a classic configuration trap machine: the spec sheet invites expensive step-ups.", "If you do not need GPU headroom, the XPS 13 or a MacBook Air is often cleaner value."],
    marketingPositioning: ["Dell's creative-premium bridge between ultraportable and workstation", "A product designed to make performance upgrades feel inevitable"],
    summary: "A valid creator laptop if you need the headroom, but the config ladder needs discipline.",
    shortPitch: "Best Dell if display and creator headroom matter more than price calm.",
    priceStory: "The value case depends heavily on staying away from stacked upgrade options.",
    upsellPressure: 90,
    discountPressure: 76,
    lockInPressure: 30
  }),
  product({
    id: "yoga-slim-7i",
    name: "Lenovo Yoga Slim 7i",
    brand: "Lenovo",
    category: "laptops",
    tier: "Value premium",
    price: 1099,
    msrp: 1199,
    attributes: { performance: 86, battery: 85, portability: 86, display: 88, gaming: 50, longevity: 78, software: 79, value: 87 },
    ecosystems: ["windows"],
    useCaseTags: ["school", "coding", "travel", "hybrid-work"],
    strengths: ["Balanced hardware for the price", "Good screen and portability mix", "Often easier value than prestige Windows rivals"],
    tradeoffs: ["Less brand polish than Dell or Apple", "Support and resale halo are weaker"],
    pricingTrapNotes: ["The value case is strong only if you do not start mirroring premium-brand upgrades.", "Lenovo's promo-heavy pricing means full MSRP is rarely the real decision context."],
    marketingPositioning: ["A practical premium alternative", "Built to win on sensible specs rather than prestige"],
    summary: "One of the calmer Windows buys if you want solid specs without paying mainly for aura.",
    shortPitch: "Best Windows value premium laptop in this set.",
    priceStory: "Competitive hardware and common promos keep the value floor strong.",
    upsellPressure: 52,
    discountPressure: 86,
    lockInPressure: 20
  }),
  product({
    id: "legion-slim-5",
    name: "Lenovo Legion Slim 5",
    brand: "Lenovo",
    category: "laptops",
    tier: "Gaming-value",
    price: 1399,
    msrp: 1499,
    attributes: { performance: 94, battery: 68, portability: 60, display: 90, gaming: 96, longevity: 78, software: 76, value: 86 },
    ecosystems: ["windows"],
    useCaseTags: ["gaming", "content-creation", "coding"],
    strengths: ["Excellent gaming value", "Strong performance ceiling for the money", "Useful crossover option for creators who game"],
    tradeoffs: ["Battery and portability are the tax", "More laptop than most students or commuters need"],
    pricingTrapNotes: ["This can be overkill if gaming is only occasional.", "The extra GPU spend is poor value if your workload is mostly writing, browsing, and light dev."],
    marketingPositioning: ["Lenovo's aggressive performance-value machine", "Designed to look like a rational way into serious gaming power"],
    summary: "A great gaming laptop for the money, but the right answer only if gaming or GPU-heavy work is truly central.",
    shortPitch: "Best gaming value laptop in the current mock set.",
    priceStory: "Hardware density is the pitch, not subtle elegance.",
    upsellPressure: 48,
    discountPressure: 78,
    lockInPressure: 20
  }),
  product({
    id: "ipad-mini",
    name: "iPad mini",
    brand: "Apple",
    category: "tablets",
    tier: "Compact tablet",
    price: 499,
    attributes: { performance: 76, battery: 80, portability: 97, display: 82, longevity: 90, software: 92, value: 84 },
    ecosystems: ["apple"],
    useCaseTags: ["reading", "travel", "commute"],
    strengths: ["Easy to hold and carry", "Best reading/travel size in the lineup", "Strong Apple ecosystem compatibility"],
    tradeoffs: ["Screen is small for split work", "Accessory story is limited compared with larger iPads"],
    pricingTrapNotes: ["If you add high-end storage and accessories, it stops being the simple-value option it appears to be.", "A larger tablet may be better value if you expect real productivity use."],
    marketingPositioning: ["Apple's compact tablet niche", "Sold on portability and lifestyle fit more than broad utility"],
    summary: "The right tablet when hand feel, reading comfort, and travel ease matter more than productivity ambition.",
    shortPitch: "Best tablet for reading and travel-first use.",
    priceStory: "Reasonable entry price, but expensive if you accessorize heavily.",
    upsellPressure: 64,
    discountPressure: 18,
    lockInPressure: 90
  }),
  product({
    id: "ipad-air-11",
    name: "iPad Air 11",
    brand: "Apple",
    category: "tablets",
    tier: "Mainstream premium tablet",
    price: 699,
    attributes: { performance: 88, battery: 86, portability: 88, display: 87, longevity: 92, software: 94, value: 80 },
    ecosystems: ["apple"],
    useCaseTags: ["school", "travel", "content-creation", "hybrid-work"],
    strengths: ["Balanced Apple tablet", "Strong app ecosystem", "Enough power for notes, drawing, and light creative work"],
    tradeoffs: ["Accessory costs move the total quickly", "The Pro exists mainly to tempt you upward"],
    pricingTrapNotes: ["Keyboard and Pencil are where the total-cost story changes.", "The Air is often the rational stopping point in Apple's tablet ladder."],
    marketingPositioning: ["Apple's mainstream aspirational tablet", "Designed to feel like the smart middle between base and Pro"],
    summary: "A balanced iPad for people who want a flexible Apple tablet without fully entering Pro pricing.",
    shortPitch: "Best mainstream iPad for most mixed-use buyers.",
    priceStory: "Feels reasonable inside Apple's premium ladder, but accessories matter.",
    upsellPressure: 82,
    discountPressure: 18,
    lockInPressure: 92
  }),
  product({
    id: "ipad-pro-11",
    name: "iPad Pro 11",
    brand: "Apple",
    category: "tablets",
    tier: "Pro tablet",
    price: 999,
    attributes: { performance: 98, battery: 88, portability: 86, display: 98, longevity: 93, software: 95, value: 66 },
    ecosystems: ["apple"],
    useCaseTags: ["content-creation", "hybrid-work", "travel"],
    strengths: ["Display and performance are elite", "Excellent for drawing and media work", "Premium Apple tablet hardware"],
    tradeoffs: ["Very easy to overbuy", "Accessories push the total into laptop territory"],
    pricingTrapNotes: ["This is often a laptop-sized spend once accessories are included.", "If your main tasks are reading, notes, and streaming, the Air is usually the smarter buy."],
    marketingPositioning: ["Apple's halo tablet", "Aspirational and creator-led rather than purely rational"],
    summary: "An incredible tablet for users who genuinely exploit the display and performance ceiling, but not the calmest value choice.",
    shortPitch: "Best iPad only if the pro-grade screen and speed really matter.",
    priceStory: "Premium pricing is justified on capability and industrial design, not thrift.",
    upsellPressure: 92,
    discountPressure: 16,
    lockInPressure: 92,
    accessoryBurden: 20
  }),
  product({
    id: "galaxy-tab-s10-fe",
    name: "Galaxy Tab S10 FE",
    brand: "Samsung",
    category: "tablets",
    tier: "Value large tablet",
    price: 529,
    msrp: 599,
    attributes: { performance: 74, battery: 84, portability: 82, display: 83, longevity: 78, software: 80, value: 88 },
    ecosystems: ["android", "samsung"],
    useCaseTags: ["school", "reading", "travel"],
    strengths: ["Large-screen value", "Often bundled with pen offers", "Good note-taking value"],
    tradeoffs: ["Performance ceiling is limited", "Software polish is below iPad"],
    pricingTrapNotes: ["Samsung promos can make the higher Tab tier surprisingly close in price.", "This only stays excellent value if your tasks remain light to moderate."],
    marketingPositioning: ["Samsung's keep-them-in-the-funnel tablet", "A value anchor inside the Galaxy tab lineup"],
    summary: "A good large Android tablet for students and note-takers who want decent value and a bigger screen.",
    shortPitch: "Best Samsung tablet value play.",
    priceStory: "Often helped by visible bundle promotions and launch incentives.",
    upsellPressure: 52,
    discountPressure: 80,
    lockInPressure: 65
  }),
  product({
    id: "galaxy-tab-s10-plus",
    name: "Galaxy Tab S10+",
    brand: "Samsung",
    category: "tablets",
    tier: "Premium Android tablet",
    price: 949,
    msrp: 999,
    attributes: { performance: 90, battery: 88, portability: 78, display: 94, longevity: 80, software: 84, value: 76 },
    ecosystems: ["android", "samsung"],
    useCaseTags: ["content-creation", "hybrid-work", "travel"],
    strengths: ["Excellent display", "Better creative and multitasking headroom", "More premium than value Android tablets"],
    tradeoffs: ["Still feels expensive for a tablet", "Accessory costs matter here too"],
    pricingTrapNotes: ["Samsung's bundles can disguise how close this gets to laptop pricing.", "If you mainly read, browse, and take notes, the FE is often cleaner value."],
    marketingPositioning: ["Samsung's high-end Android tablet", "Built to signal premium media and productivity"],
    summary: "A strong Android tablet when display quality and premium multitasking matter, but not the cheapest way to get them.",
    shortPitch: "Best premium Android tablet for media and multitasking.",
    priceStory: "Promo timing matters to whether this feels compelling or indulgent.",
    upsellPressure: 72,
    discountPressure: 72,
    lockInPressure: 68,
    accessoryBurden: 14
  }),
  product({
    id: "pixel-tablet-2",
    name: "Pixel Tablet 2",
    brand: "Google",
    category: "tablets",
    tier: "Home + casual tablet",
    price: 599,
    attributes: { performance: 78, battery: 81, portability: 84, display: 84, longevity: 84, software: 88, value: 82 },
    ecosystems: ["android", "google"],
    useCaseTags: ["reading", "travel", "hybrid-work"],
    strengths: ["Simple Google software experience", "Good casual tablet value", "Fits well if your home stack is already Google-first"],
    tradeoffs: ["Not the most ambitious productivity tablet", "Accessory ecosystem is thinner than Apple and Samsung"],
    pricingTrapNotes: ["The dock and accessory story can add up if you try to turn it into more than it wants to be.", "For heavy creative work, it is not the right tool."],
    marketingPositioning: ["Google's helpful-home-meets-tablet device", "A casual, friendly tablet rather than a pro instrument"],
    summary: "A clean Google tablet for media, reading, and light productivity without pretending to replace a laptop.",
    shortPitch: "Best Google tablet if you want simplicity over tablet ambition.",
    priceStory: "Usually sold on ease, software feel, and home-device synergy.",
    upsellPressure: 38,
    discountPressure: 54,
    lockInPressure: 60
  }),
  product({
    id: "surface-pro-12",
    name: "Surface Pro 12",
    brand: "Microsoft",
    category: "tablets",
    tier: "Flexible hybrid value",
    price: 849,
    attributes: { performance: 82, battery: 76, portability: 91, display: 86, longevity: 80, software: 87, value: 82 },
    ecosystems: ["windows", "microsoft"],
    useCaseTags: ["school", "travel", "hybrid-work", "coding"],
    strengths: ["Very flexible form factor", "Windows apps and touch are both available", "Portable enough to replace some laptop use cases"],
    tradeoffs: ["Keyboard and pen raise total cost", "Battery is not class-leading"],
    pricingTrapNotes: ["The base tablet price does not tell the whole story without accessories.", "If you want a tablet first, a pure tablet may still be the better value."],
    marketingPositioning: ["Microsoft's do-more-than-a-tablet option", "Positioned as a flexible alternative to both tablet and laptop"],
    summary: "Best when you want Windows flexibility in a light body and accept that accessories are part of the real cost.",
    shortPitch: "Best Windows-first tablet-hybrid for flexibility.",
    priceStory: "The value case hinges on how much you need Windows and pen support.",
    upsellPressure: 68,
    discountPressure: 62,
    lockInPressure: 58,
    accessoryBurden: 24
  }),
  product({
    id: "surface-pro-13",
    name: "Surface Pro 13",
    brand: "Microsoft",
    category: "tablets",
    tier: "Premium hybrid",
    price: 1099,
    attributes: { performance: 88, battery: 80, portability: 86, display: 92, longevity: 82, software: 89, value: 75 },
    ecosystems: ["windows", "microsoft"],
    useCaseTags: ["coding", "hybrid-work", "content-creation", "travel"],
    strengths: ["Better work canvas than smaller hybrids", "Strong display and flexibility combo", "Copilot+ and Windows continuity make sense here"],
    tradeoffs: ["Can approach laptop pricing quickly", "Still not the longest-lasting battery machine"],
    pricingTrapNotes: ["Keyboard and pen add substantially to the total.", "If you know you want a clamshell laptop, a Surface Laptop can be the cleaner value."],
    marketingPositioning: ["Microsoft's premium 2-in-1 pitch", "Sold as a serious work surface that still behaves like a tablet"],
    summary: "A compelling choice if touch, pen, and Windows matter together, but a premium one once accessories are included.",
    shortPitch: "Best premium Surface hybrid for mixed tablet and desk use.",
    priceStory: "The real bill is almost always higher than the tablet sticker.",
    upsellPressure: 74,
    discountPressure: 60,
    lockInPressure: 58,
    accessoryBurden: 24
  }),
  product({
    id: "airpods-pro-2",
    name: "AirPods Pro 2",
    brand: "Apple",
    category: "headphones",
    tier: "Premium earbuds",
    price: 249,
    msrp: 269,
    attributes: { audio: 86, battery: 77, portability: 97, comfort: 88, gaming: 70, longevity: 82, software: 95, value: 82 },
    ecosystems: ["apple"],
    useCaseTags: ["commute", "travel", "hybrid-work"],
    strengths: ["Best Apple convenience", "Easy carry and very strong noise control", "Excellent software integration for Apple users"],
    tradeoffs: ["Battery is good, not class-leading", "Value drops outside the Apple ecosystem"],
    pricingTrapNotes: ["Much of the premium is convenience, not only audio quality.", "If you are not deep in Apple, Sony and Bose become harder to ignore."],
    marketingPositioning: ["Apple's frictionless daily audio tool", "Convenience-led premium"],
    summary: "A very strong everyday earbud if you already live in Apple hardware.",
    shortPitch: "Best earbuds for Apple users who value convenience as much as sound.",
    priceStory: "The premium is justified mainly by ecosystem smoothness and noise-canceling polish.",
    upsellPressure: 72,
    discountPressure: 42,
    lockInPressure: 94
  }),
  product({
    id: "airpods-max",
    name: "AirPods Max",
    brand: "Apple",
    category: "headphones",
    tier: "Luxury over-ear",
    price: 549,
    attributes: { audio: 90, battery: 74, portability: 58, comfort: 84, gaming: 62, longevity: 80, software: 94, value: 62 },
    ecosystems: ["apple"],
    useCaseTags: ["travel", "hybrid-work", "content-creation"],
    strengths: ["Premium build and Apple integration", "Strong ANC and spatial features", "Feels very cohesive in the Apple stack"],
    tradeoffs: ["Heavy and not especially portable", "Price remains high versus strong competitors"],
    pricingTrapNotes: ["This is a prestige-heavy headphone purchase.", "The daily gain over Sony or Bose is often smaller than the price delta."],
    marketingPositioning: ["Apple's luxury audio object", "A prestige step that also deepens ecosystem attachment"],
    summary: "A premium Apple over-ear choice for users who care about integration and design, not a calm value buy.",
    shortPitch: "Best Apple over-ear only if the ecosystem and design are worth real money to you.",
    priceStory: "A premium anchor product first, rational everyday buy second.",
    upsellPressure: 90,
    discountPressure: 18,
    lockInPressure: 94
  }),
  product({
    id: "sony-wh1000xm6",
    name: "Sony WH-1000XM6",
    brand: "Sony",
    category: "headphones",
    tier: "Flagship over-ear",
    price: 399,
    attributes: { audio: 93, battery: 89, portability: 74, comfort: 90, gaming: 72, longevity: 84, software: 82, value: 85 },
    ecosystems: ["open", "sony"],
    useCaseTags: ["travel", "commute", "hybrid-work", "content-creation"],
    strengths: ["Excellent sound and ANC balance", "Battery is strong", "Comfort is safer than most flagships"],
    tradeoffs: ["App polish is fine, not magical", "Still expensive if your use is mostly casual"],
    pricingTrapNotes: ["Sony's flagship premium is usually justified, but not everyone needs it.", "If portability matters most, premium earbuds may solve the problem better."],
    marketingPositioning: ["Sony's category-leader halo headphone", "Sold on completeness rather than ecosystem lock-in"],
    summary: "A flagship over-ear recommendation that makes sense for many travelers and focus-heavy users because the fundamentals are strong.",
    shortPitch: "Best all-around premium over-ear headphone in the dataset.",
    priceStory: "The premium is more about consistent excellence than ecosystem friction.",
    upsellPressure: 64,
    discountPressure: 48,
    lockInPressure: 30
  }),
  product({
    id: "sony-wf1000xm6",
    name: "Sony WF-1000XM6",
    brand: "Sony",
    category: "headphones",
    tier: "Flagship earbuds",
    price: 299,
    attributes: { audio: 91, battery: 80, portability: 94, comfort: 82, gaming: 69, longevity: 80, software: 80, value: 82 },
    ecosystems: ["open", "sony"],
    useCaseTags: ["commute", "travel", "content-creation"],
    strengths: ["Excellent sound in earbud form", "Portable and premium", "Good compromise between quality and carry ease"],
    tradeoffs: ["Fit can be more personal than over-ear options", "Still expensive for an earbud"],
    pricingTrapNotes: ["The flagship earbud premium is only justified if you actually care about the extra sound refinement.", "For work calls and convenience alone, cheaper buds often get close enough."],
    marketingPositioning: ["Sony's best-pocketable audio story", "Premium earbuds sold on audio-first credibility"],
    summary: "A high-end earbud for users who want great sound without carrying full-size headphones.",
    shortPitch: "Best premium earbud for sound-first buyers outside one ecosystem.",
    priceStory: "A fair premium if you care about audio, less fair if you mostly want convenience.",
    upsellPressure: 60,
    discountPressure: 42,
    lockInPressure: 24
  }),
  product({
    id: "bose-qc-ultra",
    name: "Bose QuietComfort Ultra",
    brand: "Bose",
    category: "headphones",
    tier: "Comfort flagship",
    price: 429,
    attributes: { audio: 89, battery: 83, portability: 70, comfort: 95, gaming: 68, longevity: 82, software: 80, value: 77 },
    ecosystems: ["open"],
    useCaseTags: ["travel", "hybrid-work", "commute"],
    strengths: ["Exceptional comfort", "Reliable ANC and easy long-session wear", "Low-drama premium experience"],
    tradeoffs: ["Not the best value in raw specs", "Still pricey for the gain over the regular QuietComfort"],
    pricingTrapNotes: ["This is often the pay-for-comfort option, which may or may not matter enough to you.", "If you wear them for shorter sessions, the standard QC is usually the calmer buy."],
    marketingPositioning: ["Bose's reassurance flagship", "Comfort and polish sold as the premium"],
    summary: "A great buy for heavy travelers and focus users who know comfort is worth paying for.",
    shortPitch: "Best comfort-led premium over-ear.",
    priceStory: "The premium is mainly about comfort certainty and polish, not massive feature separation.",
    upsellPressure: 74,
    discountPressure: 40,
    lockInPressure: 20
  }),
  product({
    id: "bose-qc",
    name: "Bose QuietComfort",
    brand: "Bose",
    category: "headphones",
    tier: "Mainstream premium",
    price: 299,
    msrp: 349,
    attributes: { audio: 84, battery: 88, portability: 72, comfort: 93, gaming: 66, longevity: 81, software: 78, value: 88 },
    ecosystems: ["open"],
    useCaseTags: ["travel", "commute", "hybrid-work"],
    strengths: ["Excellent value relative to Bose flagship", "Comfort remains excellent", "Frequently discounted to an even stronger position"],
    tradeoffs: ["Sound is good rather than best-in-class", "The flagship still edges it on polish"],
    pricingTrapNotes: ["This often exposes the flagship Ultra as a comfort-upgrade luxury rather than a necessity.", "When discounted, this is one of the clearer value buys in premium over-ear audio."],
    marketingPositioning: ["The Bose 'smart middle'", "Positioned to feel safer and more sensible than the Ultra"],
    summary: "A calm premium over-ear pick when comfort, battery, and value matter more than flagship bragging rights.",
    shortPitch: "Best Bose value if you want comfort without luxury-tier spend.",
    priceStory: "A frequent-promo product with a strong value floor.",
    upsellPressure: 48,
    discountPressure: 72,
    lockInPressure: 18
  }),
  product({
    id: "galaxy-buds-3-pro",
    name: "Galaxy Buds 3 Pro",
    brand: "Samsung",
    category: "headphones",
    tier: "Galaxy premium earbuds",
    price: 219,
    msrp: 249,
    attributes: { audio: 84, battery: 79, portability: 95, comfort: 83, gaming: 71, longevity: 78, software: 86, value: 84 },
    ecosystems: ["android", "samsung"],
    useCaseTags: ["commute", "travel", "hybrid-work"],
    strengths: ["Convenient for Galaxy users", "Portable and easy to carry", "Often promo-friendly"],
    tradeoffs: ["Best value mainly inside Samsung's ecosystem", "Sound quality is good but not category-leading"],
    pricingTrapNotes: ["Galaxy bundle promos can make these feel almost free, which can distort the standalone value story.", "Outside Samsung phones, the advantage narrows."],
    marketingPositioning: ["Samsung's ecosystem earbud", "A convenience-led upsell that makes the phone stack feel fuller"],
    summary: "A sensible Galaxy earbud if ecosystem integration matters and promo pricing is active.",
    shortPitch: "Best Samsung earbud for everyday carry and ecosystem ease.",
    priceStory: "Often strengthened by bundles rather than purely by standalone value.",
    upsellPressure: 56,
    discountPressure: 74,
    lockInPressure: 72
  }),
  product({
    id: "pixel-buds-pro-2",
    name: "Pixel Buds Pro 2",
    brand: "Google",
    category: "headphones",
    tier: "Pixel premium earbuds",
    price: 229,
    attributes: { audio: 82, battery: 82, portability: 94, comfort: 84, gaming: 68, longevity: 79, software: 88, value: 82 },
    ecosystems: ["android", "google"],
    useCaseTags: ["commute", "travel", "hybrid-work"],
    strengths: ["Clean Google Assistant and Android fit", "Portable and comfortable", "Good everyday balance"],
    tradeoffs: ["Sound is solid rather than class-leading", "Value is best for Pixel and Google-centric buyers"],
    pricingTrapNotes: ["The convenience premium is more important here than absolute audio leadership.", "If you care more about sound than ecosystem, Sony is usually the stronger buy."],
    marketingPositioning: ["Google's software-first earbud", "Sold on helpfulness and Android fit"],
    summary: "A smart everyday Android earbud, especially for Pixel users who value software polish and ease.",
    shortPitch: "Best Google earbud for convenience-led Android use.",
    priceStory: "Moderate premium mostly justified by software experience.",
    upsellPressure: 50,
    discountPressure: 56,
    lockInPressure: 66
  }),
  product({
    id: "apple-watch-se",
    name: "Apple Watch SE",
    brand: "Apple",
    category: "smartwatches",
    tier: "Entry Apple watch",
    price: 249,
    attributes: { battery: 72, portability: 91, display: 74, health: 76, longevity: 86, software: 94, value: 86 },
    ecosystems: ["apple"],
    useCaseTags: ["commute", "fitness", "hybrid-work"],
    strengths: ["Strong Apple ecosystem fit", "Great value for notifications and basic fitness", "Comfortable daily wear"],
    tradeoffs: ["Battery is only okay", "Health depth and display luxury are below higher Apple watches"],
    pricingTrapNotes: ["The SE is often enough if you mostly want notifications and rings.", "The step to Series 11 is meaningful only if the extra health and display features matter to you."],
    marketingPositioning: ["Apple's sensible watch", "Built to keep value-oriented Apple users in the watch funnel"],
    summary: "A smart Apple watch choice when convenience and basic health tracking matter more than flagship features.",
    shortPitch: "Best Apple Watch value for general daily use.",
    priceStory: "A relatively rational Apple wearable by comparison with the premium tiers.",
    upsellPressure: 60,
    discountPressure: 24,
    lockInPressure: 96
  }),
  product({
    id: "apple-watch-series-11",
    name: "Apple Watch Series 11",
    brand: "Apple",
    category: "smartwatches",
    tier: "Mainstream premium",
    price: 429,
    attributes: { battery: 78, portability: 88, display: 92, health: 88, longevity: 89, software: 96, value: 78 },
    ecosystems: ["apple"],
    useCaseTags: ["fitness", "commute", "hybrid-work", "travel"],
    strengths: ["Excellent display and software polish", "Good health balance for most users", "Feels complete without being enormous"],
    tradeoffs: ["Battery is still not an endurance story", "Price climbs fast with premium materials or LTE"],
    pricingTrapNotes: ["Apple's case materials and connectivity upgrades can be poor value for many buyers.", "If notifications and general fitness are your main goals, the SE often gets close enough."],
    marketingPositioning: ["Apple's default premium watch", "The watch most buyers are meant to rationalize as the right middle"],
    summary: "A balanced Apple Watch for users who want the full mainstream Apple wearable experience without going Ultra.",
    shortPitch: "Best mainstream Apple Watch for most ecosystem buyers.",
    priceStory: "The ladder above the SE is mostly justified through polish and health refinement.",
    upsellPressure: 78,
    discountPressure: 18,
    lockInPressure: 96
  }),
  product({
    id: "apple-watch-ultra-3",
    name: "Apple Watch Ultra 3",
    brand: "Apple",
    category: "smartwatches",
    tier: "Adventure flagship",
    price: 799,
    attributes: { battery: 90, portability: 66, display: 96, health: 93, longevity: 92, software: 96, value: 66 },
    ecosystems: ["apple"],
    useCaseTags: ["fitness", "outdoors", "travel"],
    strengths: ["Battery and durability are excellent for Apple", "Great health and outdoor depth", "Very premium hardware"],
    tradeoffs: ["Big and expensive", "A clear overbuy if you mostly want daily notifications"],
    pricingTrapNotes: ["This is an aspiration watch for many buyers, not the rational default.", "If you are not outdoors often or training seriously, the Series 11 is usually cleaner value."],
    marketingPositioning: ["Apple's halo adventure watch", "Aspirational endurance product that makes the Series model feel moderate"],
    summary: "A great fit for serious outdoor or endurance users in the Apple ecosystem, but not the calm default recommendation.",
    shortPitch: "Best Apple Watch only if endurance and rugged use are central.",
    priceStory: "A high-price wearable justified on capability ceiling and identity.",
    upsellPressure: 90,
    discountPressure: 10,
    lockInPressure: 96
  }),
  product({
    id: "galaxy-watch-fe",
    name: "Galaxy Watch FE",
    brand: "Samsung",
    category: "smartwatches",
    tier: "Value Galaxy watch",
    price: 199,
    msrp: 229,
    attributes: { battery: 76, portability: 90, display: 78, health: 79, longevity: 76, software: 84, value: 88 },
    ecosystems: ["android", "samsung"],
    useCaseTags: ["fitness", "commute", "hybrid-work"],
    strengths: ["Good value for Android users", "Light and comfortable", "Often promoted aggressively"],
    tradeoffs: ["Battery and display are not premium", "Long-term polish is more limited than pricier watches"],
    pricingTrapNotes: ["This is most compelling when Samsung promotions are active.", "For casual use, the FE often exposes higher Galaxy watches as optional rather than necessary."],
    marketingPositioning: ["Samsung's value anchor wearable", "Built to keep buyers in the Galaxy wearable funnel"],
    summary: "A sensible Android smartwatch if you want value and daily convenience more than bragging rights.",
    shortPitch: "Best Samsung smartwatch value for everyday use.",
    priceStory: "Promo-friendly pricing helps the value case.",
    upsellPressure: 42,
    discountPressure: 80,
    lockInPressure: 68
  }),
  product({
    id: "galaxy-watch-8",
    name: "Galaxy Watch 8",
    brand: "Samsung",
    category: "smartwatches",
    tier: "Mainstream Galaxy watch",
    price: 349,
    msrp: 399,
    attributes: { battery: 80, portability: 87, display: 90, health: 86, longevity: 79, software: 86, value: 80 },
    ecosystems: ["android", "samsung"],
    useCaseTags: ["fitness", "commute", "travel", "hybrid-work"],
    strengths: ["Balanced Android smartwatch", "Good display and health mix", "Often improved by trade-in and promo pricing"],
    tradeoffs: ["Still less endurance-focused than Garmin", "Premium upgrade pressure remains visible"],
    pricingTrapNotes: ["Samsung's Ultra can look more tempting than it really is for normal use.", "If you mainly want notifications and light health tracking, the FE is often enough."],
    marketingPositioning: ["Samsung's mainstream premium watch", "The model designed to feel most reasonable after seeing the Ultra"],
    summary: "A strong Android smartwatch for daily use if you want polish without the size and cost of the Ultra.",
    shortPitch: "Best Galaxy Watch balance for most Android users.",
    priceStory: "Discounts and trade-in credits often matter to the final value.",
    upsellPressure: 64,
    discountPressure: 70,
    lockInPressure: 70
  }),
  product({
    id: "galaxy-watch-ultra",
    name: "Galaxy Watch Ultra",
    brand: "Samsung",
    category: "smartwatches",
    tier: "Rugged flagship",
    price: 599,
    msrp: 649,
    attributes: { battery: 88, portability: 70, display: 94, health: 90, longevity: 84, software: 88, value: 70 },
    ecosystems: ["android", "samsung"],
    useCaseTags: ["fitness", "outdoors", "travel"],
    strengths: ["Better battery and ruggedness", "High-end display and health capability", "The right Galaxy watch for harder use"],
    tradeoffs: ["Large on the wrist", "Premium for many casual users"],
    pricingTrapNotes: ["This can be an easy overbuy if your use is mostly notifications and workouts.", "The main gains are endurance and ruggedness, not a totally different daily experience."],
    marketingPositioning: ["Samsung's halo rugged wearable", "A product designed to make the mainstream watch look moderate"],
    summary: "A powerful Android watch for users who actually value endurance and ruggedness, not just the prestige tier.",
    shortPitch: "Best Galaxy watch only if you need the rugged battery-led tier.",
    priceStory: "Promotions help, but it remains a deliberate premium watch.",
    upsellPressure: 78,
    discountPressure: 62,
    lockInPressure: 72
  }),
  product({
    id: "pixel-watch-4",
    name: "Pixel Watch 4",
    brand: "Google",
    category: "smartwatches",
    tier: "Pixel flagship",
    price: 349,
    attributes: { battery: 81, portability: 89, display: 91, health: 87, longevity: 81, software: 92, value: 82 },
    ecosystems: ["android", "google"],
    useCaseTags: ["fitness", "commute", "travel", "hybrid-work"],
    strengths: ["Very strong software feel for Android", "Good health and assistant features", "Comfortable and polished"],
    tradeoffs: ["Battery is good rather than elite", "Best fit is still inside Pixel/Google-heavy setups"],
    pricingTrapNotes: ["The LTE step-up can be easy to overpay for if you rarely leave your phone.", "Garmin can be cleaner value if battery and training depth matter more than smartwatch polish."],
    marketingPositioning: ["Google's software-forward smartwatch", "Helpful, polished, and AI-adjacent rather than ultra-rugged"],
    summary: "A balanced Android smartwatch if you care about software polish, notifications, and credible health features.",
    shortPitch: "Best Pixel watch for most Android buyers who want polish.",
    priceStory: "A mainstream premium price supported by software quality rather than rugged endurance.",
    upsellPressure: 54,
    discountPressure: 52,
    lockInPressure: 66
  }),
  product({
    id: "garmin-venu-4",
    name: "Garmin Venu 4",
    brand: "Garmin",
    category: "smartwatches",
    tier: "Fitness depth",
    price: 449,
    attributes: { battery: 96, portability: 82, display: 84, health: 95, longevity: 90, software: 76, value: 84 },
    ecosystems: ["garmin", "open"],
    useCaseTags: ["fitness", "outdoors", "travel"],
    strengths: ["Outstanding battery", "Excellent health and training depth", "Long-horizon ownership confidence is strong"],
    tradeoffs: ["Software polish for smart features lags Apple and Google", "Daily convenience is less elegant"],
    pricingTrapNotes: ["If you do not care about training depth, this can be the wrong kind of premium.", "Garmin's value appears strongest when battery and fitness metrics genuinely matter."],
    marketingPositioning: ["Garmin's serious-fitness everyday watch", "Sold on endurance and training credibility"],
    summary: "The right watch when fitness depth and battery life matter more than the slickest mainstream smartwatch UI.",
    shortPitch: "Best watch in the set for endurance-focused users.",
    priceStory: "Premium pricing is justified on health depth and battery, not smartwatch glamour.",
    upsellPressure: 52,
    discountPressure: 24,
    lockInPressure: 58
  })
];
